# Generated by Django 4.2.29 on 2026-04-01 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('source', models.CharField(choices=[('email', 'Email'), ('upload', 'Upload')], default='email', max_length=20)),
                ('from_address', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.CharField(blank=True, choices=[('llm_error', 'LLM error'), ('scan_limit', 'Scan limit reached'), ('pro_required', 'Pro plan required'), ('internal_error', 'Internal error'), ('discarded_by_rule', 'Discarded by rule')], default='', max_length=30)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('email_id', models.CharField(blank=True, default='', max_length=255)),
                ('file_b64', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, default='', max_length=100)),
                ('upload_context', models.TextField(blank=True, default='')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('upload_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
