# Generated by Django 5.0.1 on 2026-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanjob',
            old_name='summary',
            new_name='from_address',
        ),
        migrations.AddField(
            model_name='scanjob',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
