# Generated by Django 4.2.29 on 2026-04-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('llm_error', 'LLM error'), ('scan_limit', 'Scan limit reached'), ('pro_required', 'Pro plan required'), ('internal_error', 'Internal error'), ('discarded_by_rule', 'Discarded by rule'), ('gcal_disconnected', 'Google Calendar disconnected')], default='', max_length=30),
        ),
    ]
