# Generated by Django 4.2.29 on 2026-04-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_scanjob_failure_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJobStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('date', 'status', 'failure_reason')},
            },
        ),
    ]
