# Generated by Django 4.2.29 on 2026-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_dailyjobstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='discarded_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
