# Generated by Django 4.2.29 on 2026-03-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_scanjob_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('llm_error', 'LLM error'), ('scan_limit', 'Scan limit reached'), ('pro_required', 'Pro plan required'), ('internal_error', 'Internal error')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='failure_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
