# Generated by Django 6.0.4 on 2026-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_scanjob_discarded_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('llm_error', 'LLM error'), ('llm_overloaded', 'LLM overloaded (exhausted retries)'), ('scan_limit', 'Scan limit reached'), ('pro_required', 'Pro plan required'), ('internal_error', 'Internal error'), ('discarded_by_rule', 'Discarded by rule'), ('gcal_disconnected', 'Google Calendar disconnected')], default='', max_length=30),
        ),
    ]
