# Generated by Django 4.2.29 on 2026-03-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_scanjob_failure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='task_args',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
