# Generated by Django 4.2.29 on 2026-03-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_add_scanjob_task_args'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Done'), ('failed', 'Failed')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('llm_error', 'LLM error'), ('scan_limit', 'Scan limit reached'), ('pro_required', 'Pro plan required'), ('internal_error', 'Internal error')], default='', help_text='Only populated if status=failed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='emails.scanjob')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='emails_joba_created_2daf9e_idx'), models.Index(fields=['status', 'failure_reason'], name='emails_joba_status_bfe22b_idx')],
            },
        ),
    ]
