# Generated by Django 6.0.4 on 2026-04-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_refactor_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referral_max_redemptions',
            field=models.PositiveSmallIntegerField(default=12, help_text='Maximum number of times this referral code can be redeemed. Set before the code is generated — Stripe does not allow changing this after the PromotionCode is created.'),
        ),
    ]
