# Generated by Django 6.0.4 on 2026-04-12 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_referral_max_redemptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='refundrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='referral_max_redemptions',
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited. Enforced by Stripe at checkout.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_coupon_id', models.CharField(blank=True, max_length=255)),
                ('stripe_promotion_code_id', models.CharField(blank=True, max_length=255)),
                ('head', models.ForeignKey(blank=True, help_text='User who earns a refund when their redeemers pay. Null = NeverDue grant (always pays out to redeemers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='coupon_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='head_refunds', to='billing.coupon'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='referral_coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_subscription', to='billing.coupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.couponredemption'),
        ),
        migrations.AddConstraint(
            model_name='refundrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('redemption__isnull', False)), fields=('redemption', 'stripe_invoice_id'), name='unique_redemption_invoice'),
        ),
        migrations.AddConstraint(
            model_name='refundrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('coupon_head__isnull', False)), fields=('coupon_head', 'stripe_invoice_id'), name='unique_head_invoice'),
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='user_coupon',
        ),
        migrations.AlterUniqueTogether(
            name='couponredemption',
            unique_together={('coupon', 'user')},
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
