# Generated by Django 4.2.29 on 2026-03-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(blank=True, choices=[('allow', 'Allow'), ('block', 'Block'), ('categorize', 'Categorize'), ('discard', 'Discard')], max_length=20),
        ),
        migrations.DeleteModel(
            name='FilterRule',
        ),
    ]
