# Generated by Django 5.0.1 on 2026-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_pending_expires_at_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pending_concern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
