# Generated by Django 4.2.29 on 2026-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
