# Generated by Django 4.2.29 on 2026-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='gcal_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
