# Generated by Django 4.2.29 on 2026-03-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_event_color_event_gcal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gcal_color_id',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
