# Generated by Django 4.2.29 on 2026-03-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rule_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['rule_type', 'created_at']},
        ),
    ]
