# Generated by Django 4.2.29 on 2026-04-03 04:08

from django.db import migrations, models


def forward(apps, schema_editor):
    """Existing users with revoke_google_on_logout=True get save_to_gcal=True (still save)."""
    # New field default is True, which is correct for all existing users:
    # they were using GCal before this change.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='revoke_google_on_logout',
        ),
        migrations.AddField(
            model_name='user',
            name='save_to_gcal',
            field=models.BooleanField(default=True),
        ),
    ]
