# Generated by Django 4.2.29 on 2026-03-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='revoke_google_on_logout',
            field=models.BooleanField(default=False),
        ),
    ]
