# Generated by Django 5.0.1 on 2026-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_delete_past_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_from_gcal_on_cleanup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='past_event_retention_days',
            field=models.IntegerField(default=30),
        ),
    ]
