# Generated by Django 5.0.1 on 2026-03-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auto_delete_past_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_auto_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='auto_delete_past_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='English', max_length=10),
        ),
    ]
