# Generated by Django 5.0.1 on 2026-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_timezone_user_timezone_auto_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='priority_color_high',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='user',
            name='priority_color_low',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='priority_color_medium',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='priority_color_urgent',
            field=models.IntegerField(default=11),
        ),
    ]
