# Generated by Django 4.2.29 on 2026-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_priority_color_high_user_priority_color_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcal_channel_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gcal_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gcal_channel_resource_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
