# Generated by Django 4.2.29 on 2026-03-28 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_gcal_channel_expiration_user_gcal_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_input_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_output_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('input_cost_per_million', models.DecimalField(decimal_places=4, default='3.0000', max_digits=8)),
                ('output_cost_per_million', models.DecimalField(decimal_places=4, default='15.0000', max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month'),
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
