# Generated by Django 4.2.29 on 2026-04-05 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bug', '🐛 Something is broken'), ('feature', '💡 Feature request'), ('howto', '❓ How do I…?'), ('perf', '⚡ Something is slow'), ('privacy', '🔐 Privacy / account issue')], max_length=20)),
                ('body', models.TextField()),
                ('llm_answer', models.TextField(blank=True)),
                ('gh_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_user', 'Awaiting user'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
