# Generated by Django 4.2.29 on 2026-04-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', '🐛 Something is broken'), ('feature', '💡 Feature request'), ('howto', '❓ How do I…?'), ('perf', '⚡ Something is slow'), ('privacy', '🔐 Privacy / account issue')], default='bug', max_length=20),
        ),
    ]
